# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

os: osx
osx_image: xcode12.5
cache: carthage
before_install:
  - carthage update --platform iOS --use-xcframeworks --no-use-binaries --cache-builds
script:
  - set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace DDMvvm.xcworkspace -scheme DDMvvm -sdk iphonesimulator14.5 ONLY_ACTIVE_ARCH=NO | xcpretty
